### ISSUE TITLE
Template mini1  <?php echo toc(2,3);?> und Menulevels

### ISSUE THREAD

**Issue by lck-git** [TN03/XH_split#13]
1.) Für die XH_split Tests wäre es sinnvoll den Menü-Aufruf zu ändern:
`<?php echo toc(2,3);?>`
zu
`<?php echo toc(2,max($l));?>`

2.) Im Beispiel-Content eventuell auch gleich Menülevels bis ml9 anlegen.

**Comment by TN03** [comment]
@lck-git: Hast Du vielleicht schon ein passend modifiziertes Template zur Hand, bei dem dann auch alle Unterseiten in der Navigation halbwegs lesbar angezeigt werden??

**Comment by frase-git** [comment]
http://cmsimpleforum.com/viewtopic.php?f=16&t=11966&hilit=template&start=100#p55706

**Comment by lck-git** [comment]
@TN03: Leider momentan nicht, aber [mini3](http://svasti.de/?Templates/Mini3) wäre sehr gut dafür geeignet, finde ich.
Ist ohne Anpassung verwendbar und die Menülevel werden übersichtlich dargestellt.

Andere geeignete Templates:
[mini1x](http://cmsimpleforum.com/viewtopic.php?f=16&t=11966&p=55706&hilit=template#p55706) von Frank
mini2
responsivehtml
n6200tbisGPL3
gonzo-h

**Comment by cmb69** [comment]
Ich habe mir gerade mal mini1x und mini3 angeschaut, und beide haben schon noch kleine Probleme mit tiefen Verschachtelungen. Bei mini1 ist das Menü bald zu schmal, und der Inhalt läuft in den Rahmen über. Bei mini3 wird im Menü nur bis Level 3 eingerückt (wobei das wenigstens keine Probleme mit dem schmalen Menü macht),

**Comment by TN03** [comment]
@frase-git mini1x schaut irgendwie "kaputt" aus ;). Aber vielleicht erlaubst Du ja, dass wir dein neues Template http://www.fhseidel.de/cmsxh/fhs-left-right-split/ dafür nehmen. Der Content wäre ja auch fast ausreichend.

**Comment by frase-git** [comment]
@TN03 Klar doch, dafür mach' ich's ja.
Bin aber noch nicht fertig. Muss noch an einigen Stellen schrauben.
Vorschläge für Demo-Inhalt?

**Comment by cmb69** [comment]
> Vorschläge für Demo-Inhalt?

Bei "Das Template" würde ich nur die Einleitung etwas ändern (halt nicht "dieses Template ist eine Studie", sondern "XH_split ist eine Studie" etc.). "Struktur-Test" ist okay (vielleicht noch etwas mehr Blindtext). "Download" könnte auf dieses Github-Repo verweisen.

**Comment by TN03** [comment]
@cmb69 Damit hast Du eigentlich schon alles gesagt.
Super!

**Comment by frase-git** [comment]
Close?

**Comment by TN03** [comment]
> Close?
Ja, ist erledigt spätestens mit https://github.com/TN03/XH_split/commit/f89a28bb87480eac8e7951a2b42fa9babe02151f
