### ISSUE TITLE
Issues with CKEditor in advanced mode

### ISSUE THREAD

**Issue by cmb69** [TN03/XH_split#16]
The CKEditor doesn't work well with newly created pages (Pagemanager) in advanced mode, see <http://cmsimpleforum.com/viewtopic.php?f=16&t=11966&start=160#p55822>.

Not sure how to solve that best.

**Comment by TN03** [comment]
Seems that's fixed with the latest CKEditor 4.6.0, see commit 24ad42890f5ffecd2a2beba42677032948914e53.

**Comment by cmb69** [comment]
Yeah, looks good now. @frase-git Kannst Du das bitte mal gegentesten?

**Comment by frase-git** [comment]
Gemach, gemach.
Ich sein alter Mann.
;-)

**Comment by frase-git** [comment]
Gegengetestet.
Scheint zu funktionieren.

**Comment by cmb69** [comment]
Super. Dann schließe ich das Ticket mal.
