### ISSUE TITLE
Some footer links in the default template are broken

### ISSUE THREAD

**Issue by cmb69** [TN03/XH_split#19]
The default template fhs-left-right-split has links to "Kontakt" and "Impressum" in the footer, but neither does work (404 Not found). I don't think that we want to have a real mailform, and as it's [no more possible to have a page called "mailform"](http://cmsimpleforum.com/viewtopic.php?f=29&t=6058), I suggest to change the "Kontakt" link, and to add the respective pages "Kontakt" and "Impressum" with appropriate demo content.

**Comment by frase-git** [comment]
I will do so.

**Comment by frase-git** [comment]
OK?
Close?

**Comment by TN03** [comment]
> OK?
Close?

Ja, ist erledigt spätestens mit https://github.com/TN03/XH_split/commit/f89a28bb87480eac8e7951a2b42fa9babe02151f
