### ISSUE TITLE
Limit menulevels and fix levelcatch

### ISSUE THREAD

**Issue by TN03** [TN03/XH_split#2]
See: http://cmsimpleforum.com/viewtopic.php?f=16&t=11966&start=60#p55640

**Comment by cmb69** [comment]
After further consideration, I suggest to stick with the configurable levelcatch (at least for this project), because it is [supposed to be a feature](http://forum.cmsimple-xh.dk/?f=2&t=5822#p30668) (user#2 is Peter Harteg himself).
