### ISSUE TITLE
Suche, Suchergebnisse - h1 und andere Seitenüberschrift

### ISSUE THREAD

**Issue by lck-git** [TN03/XH_split#31]
Problem Suche, gefundene Seiten: h1 wird in der gefundenen Seite unterschlagen, nicht ausgegeben.
Beispiel:
Sucht man nach "und" und ruft dann unter "Suchergebnis" irgendeine Seite auf, z.B. "Templates", wird "Templates" nur als schlichter Text angezeigt, ohne h1.

Das Problem mit den Suchergebnissen bei [geänderter Seitenüberschrift](https://github.com/cmsimple-xh/cmsimple-xh/pull/13)  ist ja schon bekannt.
Jetzt habe ich aber festgestellt, dass bestimmte Suchanfragen doch die Seite finden.
Beispiel Seite "Start", geänderte Seitenüberschrift ist "Glückwunsch!"
Sucht man im Demo-Content nach "Glü", "Glück" usw. oder auch "wunsch" oder "uns", wird die Seite nicht gefunden.
Sucht man aber nach "w", "wu", "wun", "u", "un", "sch" "nsch" wird die Seite "Start" gefunden!?

**Comment by frase-git** [comment]
Verrückt!
Kann ich alles bestätigen.
Das ist ein so schräges Verhalten. Das muss mir mal einer erklären.

**Comment by cmb69** [comment]
> Sucht man nach "und" und ruft dann unter "Suchergebnis" irgendeine Seite auf, z.B. "Templates", wird "Templates" nur als schlichter Text angezeigt, ohne h1.

[Das](https://github.com/TN03/XH_split/commit/5568652f4f518f0b743a42ee4444f4a8c3e604d7#commitcomment-20537611) sieht mir nach einem Bug aus.

> Beispiel Seite "Start", geänderte Seitenüberschrift ist "Glückwunsch!"
Sucht man im Demo-Content nach "Glü", "Glück" usw. oder auch "wunsch" oder "uns", wird die Seite nicht gefunden.
Sucht man aber nach "w", "wu", "wun", "u", "un", "sch" "nsch" wird die Seite "Start" gefunden!?

Der Fix für alternative Seitenheadings ist in XH_split noch nicht integriert. Gefunden wird in Wirklichkeit das Wort "verschwunden" (oder ein anderes). Das Hightlighting hebt dann auch die geänderte Überschrift hervor.

**Comment by TN03** [comment]
> Das sieht mir nach einem Bug aus.

Ja, das ist natürlich Quatsch. Keine Ahnung, was mich da geritten hat.
Behoben mit https://github.com/TN03/XH_split/commit/8ec77480f8a83a089d8f573016cdaec676410925

**Comment by cmb69** [comment]
> Behoben mit 8ec7748

Dann kann dieses Issue wohl geschlossen werden.
