### ISSUE TITLE
Template fhs-simple-split Suchfeld

### ISSUE THREAD

**Issue by lck-git** [TN03/XH_split#32]
Bitte Farbe für [ Such-Feld](https://github.com/cmb69/XH_split/blob/master/source/templates/fhs-simple-split/stylesheet.css#L829) ändern. Ist momentan weiß auf weißem Hintergrund.

**Comment by frase-git** [comment]
Das soll eine "geheime" Suche sein. ;-)

Quatsch. Au Backe. Dicker Bug.
Das kommt davon, wenn man etwas lieblos und zu schnell macht.

[fhs-simple-split-upd3.zip](https://github.com/TN03/XH_split/files/716636/fhs-simple-split-upd3.zip)
Damit wird "upd2" hinfällig. Ist alles hier enthalten.

Da ich immer noch nicht pull requesten kann, muss sich jemand anderes finden, der das tut.

**Comment by cmb69** [comment]
Super, danke! Ich habe die Änderungen am Template eingespielt (commit d3c28e80). Die Flaggen gehören zu #28. :)
