### ISSUE TITLE
Fehler im Template fhs-simple-split - styles.css

### ISSUE THREAD

**Issue by frase-git** [TN03/XH_split#33]
Habe noch einen Fehler im Stylesheet gefunden.
Es ist nur eine Zeile (Zeile 3) hinzuzufügen:

@import url("accordion.css");
@import url("fonts.css");
hinzufügen:
@import url(font-awesome.min.css);

Kann das jemand manuell tun?

**Comment by cmb69** [comment]
Hm, font-awesome.min.css wird bereits von [template.htm verlinkt](https://github.com/TN03/XH_split/blob/master/source/templates/fhs-simple-split/template.htm#L14); das könnte dann wohl entfallen, oder?

Und wird fonts.css gar nicht benötigt? Falls ja, dann könnte die Datei entfernt werden.

**Comment by cmb69** [comment]
> Und wird fonts.css gar nicht benötigt? Falls ja, dann könnte die Datei entfernt werden.

Blödsinn. Ich hatte das "hinzufügen" nicht gelesen.

Die Frage nach der Verlinkung im Template bleibt aber.

**Comment by frase-git** [comment]
Sorry, ich verliere langsam selbst den Überblick.

> Die Frage nach der Verlinkung im Template bleibt aber.

Richtig.
Dort kann es jetzt raus.
Zeile 14:
`<link href="<?php echo $pth['folder']['template']?>font-awesome.min.css" rel="stylesheet" type="text/css">`

Entstanden ist der Kuddelmuddel durch viele Tests (die ich offensichtlich nicht konsequent beendet habe.)
Danke!

fonts.css definiert die Standard-Schriftarten. Wird benötigt.

---
Fazit:
@import url(font-awesome.min.css);
in stylesheet einfügen

`<link href="<?php echo $pth['folder']['template']?>font-awesome.min.css" rel="stylesheet" type="text/css">`
in template entfernen

**Comment by cmb69** [comment]
Erledigt. Danke!
