### ISSUE TITLE
Non ASCII template name ⇒ contents area missing

### ISSUE THREAD

**Issue by lck-git** [TN03/XH_split#36]
Ich weiß, Umlaute in Datei- oder Ordnernamen sollten grundsätzlich ja nicht verwendet werden, aber beim Entwickeln ist es mir passiert. Eventuell ist es ja wichtig, drum hier mal das Problem.

Sobald unter ./templates ein Template-Ordner mit Umlauten vorhanden ist (Beispiel Template "mini1_mitö") und will man die Seite editieren, ist der Editor-/Contentbereich komplett verschwunden!
Der Debug-Modus liefert keine Fehlermeldungen, aber dir Browser-Konsole:
```
Uncaught TypeError: Cannot read property 'elements' of null			?Start&edit:423 
    at Object.META_TAGS.init (?Start&edit:423)
    at onload (?Start&edit:143)
META_TAGS.init @ ?Start&edit:423
onload @ ?Start&edit:143
```
Löscht man die template.htm aus dem Template-Ordner "mini1_mitö", so ist der Editor wieder da, auch ein leerer Template-Ordner mit Umlauten im Namen bereitet keine Probleme.

In CMSimple_XH 1.6.9 gibt es das Problem nicht. Da wird auch unter Einstellungen > CMS bei der Template-Auswahl der Template-Name mit dem Umlaut korrekt angezeigt.
In XH_split steht für den Umlaut ein Fragezeichen, auch in CMSimple_XH 1.6.7 aber hier gibt es auch keine Probleme mit dem Editor-Bereich. Doch ein XH_split Problem?

**Comment by cmb69** [comment]
Wow, guter Fang! :)

Ein Teil des Problems befindet sich in [XH_split's content() Funktion](https://github.com/TN03/XH_split/blob/master/source/cmsimple/tplfuncs.php#L538-L565), die naturgemäß angepasst werden musste, um die Splitter herauszufiltern. Dabei wird der PCRE `u` Modifier verwendet, der korrektes UTF-8 voraussetzt (und andernfalls einen Fehler ergibt ⇒ false ⇒ '').

Das grundlegendere Problem ist, dass PHP unter Windows Dateinamen als UTF-16 interpretiert (soweit ich weiß; könnte auch Locale abhängig sein; und wenn ich mich nicht irre, dann wurde das bei PHP 7.1 korrigiert). Da nun page_params eine Liste von Templates für die jeweilige Seite erstellt, wird ungültiges UTF-8 nach $o geschrieben, und somit wird später das ganze $o einfach zu einem leeren String.

Einfache Lösung: die beiden relevanten `preg_replace()` sollten den `u` Modifier *nicht* verwenden – er hat hier sowieso keine besondere Funktion. Dann wird der Editor bzw. Seiteninhalt auch wieder angezeigt. Im Tab "Seite" werden unter "Seitentemplate" dann immer noch � dargestellt (REPLACEMENT CHARACTER), aber damit kann man wohl leben – Templatenamen sollten halt immer nur ASCII Zeichen verwenden.

**Comment by TN03** [comment]
> Einfache Lösung: die beiden relevanten preg_replace() sollten den u Modifier nicht verwenden – er hat hier sowieso keine besondere Funktion.

Da habe ich die Dokumentation scheinbar komplett missverstanden? Aber auch in den Kommentaren finden sich (für mich) nur widersprüchliche Aussagen.

> Im Tab "Seite" werden unter "Seitentemplate" dann immer noch � dargestellt (REPLACEMENT CHARACTER), aber damit kann man wohl leben – Templatenamen sollten halt immer nur ASCII Zeichen verwenden.

Wie wurde das in 1.6.9 behoben?

**Comment by cmb69** [comment]
> Da habe ich die Dokumentation scheinbar komplett missverstanden?

[Die](http://php.net/manual/en/reference.pcre.pattern.modifiers.php) ist tatsächlich etwas knapp, aber korrekt, soweit ich das beurteilen kann:

> This modifier turns on additional functionality of PCRE that is incompatible with Perl. Pattern and subject strings are treated as UTF-8. An invalid subject will cause the preg_* function to match nothing; an invalid pattern will trigger an error of level E_WARNING. 

Erforderlich ist der `u` Modifier nur, falls im Pattern spezielle UTF-8 Features verwendet werden, z.B. `\p{L}` (ein Unicode Buchstabe) oder `.{3}` (drei Unicode Zeichen), oder wenn das Subject explizit auf valides UTF-8 geprüft werden soll. Letzteres ist eigentlich immer sinnvoll (auch wenn es etwas länger dauert), aber in unserem Fall gibt es dann eben solche Probleme.

> Wie wurde das in 1.6.9 behoben?

Ich würde sagen, gar nicht. @lck-git Hattest Du XH 1.6.9 unter PHP 7.1 getestet? 

Jedenfalls kann man unter Windows das unterschiedliche Verhalten von PHP 7.1 und vorherigen Versionen mit dem folgenden Code sehr schön sehen:
````
file_put_contents("\xc3\x9c", "foo");
````

**Comment by lck-git** [comment]
> Ich würde sagen, gar nicht. @lck-git Hattest Du XH 1.6.9 unter PHP 7.1 getestet?

Nein, online unter PHP-Version 5.6.28

**Comment by cmb69** [comment]
> Nein, online unter PHP-Version 5.6.28

Ah, das war dann vermutlich kein Windows-Server, sondern ein *nix mit UTF-8 Dateisystem (oder PHP hat da passend "übersetzt").

**Comment by lck-git** [comment]
Also, ich habe gerade nochmal online XH_split und CMSimple_XH 1.6.7 und 1.6.9 mit Templatenamen getestet, die Umlaute enthalten. Fazit: keine Probleme, die Namen werden auch so angezeigt, mit Umlauten und ohne Fragezeichen. Scheint nur unter Windows lokal und evtl. Windows-Server Probleme zu machen.

Edit: Server mit Apache und default_charset	UTF-8

**Comment by cmb69** [comment]
> Scheint nur unter Windows lokal und evtl. Windows-Server Probleme zu machen.

Ja genau, weil NTFS Dateinamen als UTF-16 (oder UCS-2) speichert, und diese erst ab PHP 7.1 intern übersetzt werden. Ich denke, da sollten wir aber nichts machen, außer halt die `u` Modifier zu entfernen (und vielleicht explizit zu dokumentieren, dass Template-Ordner nur ASCII Zeichen verwenden sollen – das sollte die Probleme sehr im Rahmen halten).

Ich mach das nacher – muss jetzt gleich weg.

**Comment by cmb69** [comment]
Okay, hat doch noch gepasst. :)
